apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
     volumes:
      - name: my-pv-storage
        persistentVolumeClaim:
          claimName: my-pv-claim 
     containers:
      - name: redis
        image: redis:6.2.6-alpine3.14
        ports:
        - containerPort: 6379
          name: web
        volumeMounts:
        - name: my-pv-storage
          mountPath: /data
